"""Compartilhar entre entidades

Revisão: 0011
Anterior: 0010
Criada em: 2026-10-08 12:05:01.959308
"""
from alembic import op
import sqlalchemy as sa


revision = '0011'
down_revision = '0010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('cost_centers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost_centers', schema=None) as batch_op:
        batch_op.drop_column('shared')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('shared')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('shared')

    # ### end Alembic commands ###
