"""Multimoeda

Revisão: 0007
Anterior: 0006
Criada em: 2026-10-06 13:28:34.855726
"""
from alembic import op
import sqlalchemy as sa


revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'currency', 'day', name='uq_rate_day')
    )
    # base_amount entra vazio, recebe o próprio valor (até aqui tudo era numa moeda só) e só então fica obrigatório
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_amount', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('dest_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.execute("UPDATE entries SET base_amount = amount")
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.alter_column('base_amount', existing_type=sa.Numeric(precision=15, scale=2), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_column('dest_amount')
        batch_op.drop_column('base_amount')

    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
