"""Cartão de crédito: fechamento, vencimento e limite

Revisão: 0002
Anterior: 0001
Criada em: 2026-10-06 09:21:53.119850
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closing_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('due_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('credit_limit')
        batch_op.drop_column('due_day')
        batch_op.drop_column('closing_day')

    # ### end Alembic commands ###
