"""Contatos ampliados

Revisão: 0003
Anterior: 0002
Criada em: 2026-10-06 10:46:19.158166
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=9), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('pix_key', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('bank_info', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('bank_info')
        batch_op.drop_column('pix_key')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
